name: Go Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21  # Set your Go version

      - name: Install Dependencies
        run: go mod tidy

      - name: Run Unit Tests
        run: go test -v ./greeterpb
strategy:
   matrix:
     go-version: [1.20, 1.21]
